name: Publish Docker image
on: push
jobs:
  pushtodockerhub:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: lucascosti
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: lucascosti/hello-octocat
          tag_with_ref: true
          